name: funhpc-hs
version: '0.1.0.0'
github: "eschnett/funhpc-hs"
license: Apache-2.0
author: "Erik Schnetter <schnetter@gmail.com>"
maintainer: "Erik Schnetter <schnetter@gmail.com>"
category: Distributed Computing
synopsis: Functional HPC Programming (using Haskell)
description: Functional HPC Programming (using Haskell)

extra-source-files:
  - CHANGELOG.md
  - LICENSE
  - package.yaml
  - README.md
  - stack.yaml

ghc-options:
  - -foptimal-applicative-do
  - -funbox-strict-fields
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Wno-unused-matches

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - EmptyCase
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - ParallelListComp
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators
  - TypeSynonymInstances
  - UnicodeSyntax
  # more controversial?
  - AllowAmbiguousTypes
  - MonadComprehensions
  - PackageImports
  - PolyKinds
  - TypeInType

library:
  dependencies:
    - array
    - base
    - bytestring
    - cereal
    - cereal-text
    - monad-loops
    - mpi-hs
    - text
  source-dirs: lib

executables:
  funhpc:
    source-dirs: src
    main: FunHPC.hs
    dependencies:
      - base
      - funhpc-hs
      - mpi-hs
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N

benchmarks:
  funhpc-benchmarks:
    source-dirs: bench
    main: Main.hs
    dependencies:
      - base
      - funhpc-hs
      - criterion
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N

tests:
  funhpc-test-suite:
    source-dirs: test
    main: Main.hs
    dependencies:
      - base
      - funhpc-hs
      - tasty
      - tasty-hspec
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
