# Resolver to choose a 'specific' stackage snapshot or a compiler version.
# resolver: lts-15.9
resolver: nightly-2020-04-18

# User packages to be built.
packages:
  - .

extra-deps:
  - mpi-hs-binary-0.1.1.0@sha256:0e17011c2ec371f638a7b5786f81d4f9679301d1c72291af66ed35a0326ad607,4021
