# Resolver to choose a 'specific' stackage snapshot or a compiler version.
resolver: lts-12.13

# User packages to be built.
packages:
  - .

extra-deps:
  - git: https://github.com/eschnett/mpi-hs.git
    commit: 8fe90abc8bbf6f0a3667353a5801eda71a01078b # v0.2.0.0

# Extra directories used by stack for building
extra-include-dirs:
  - /opt/local/include/openmpi-mp
  - /usr/lib/openmpi/include
extra-lib-dirs:
  - /opt/local/lib/openmpi-mp
  - /usr/lib/openmpi/lib
